# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrap and rebuild

on:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  schedule:
  - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers.
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-  

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraping
      env:
        AT_BASE_ID: ${{ secrets.AT_BASE_ID }}
        AT_API_KEY: ${{ secrets.AT_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 scrap.py
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'Łukasz Kałużny'
        author_email: lukasz@kaluzny.pro
        message: 'New scraping'
        add: '*.json'

    - uses: helaili/jekyll-action@2.1.0
      env:
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: 'gh-pages'
        token: ${{ secrets.GITHUB_TOKEN }}
